name: "Setup Eat Package Manager"
description: "Setup the Eat package manager for GNU/Linux"
branding:
  icon: terminal
  color: yellow

runs:
   using: composite
   steps:
     - shell: bash
       run: |
        echo "Welcome! This script will install Eat. Please wait..."
        echo "This should take a few minutes."
     - run: git clone https://github.com/EatInstall/Eat.git
       shell: bash
     - shell: bash
       run: |
         cd Eat
         echo "Installing PyInstaller..."
         pip install pyinstaller
         echo "Installing UPX..."
         sudo apt-get update
         sudo apt-get install upx -y
         echo "Compiling eat.py"
         pyinstaller --console --onefile --name "eat" "eat.py"
         echo "Compiling eat-install.py"
         pyinstaller --console --onefile --name "eatinst" "eat-install.py"
         echo "Installing..."
         sudo install ./dist/eat /usr/bin/eat
         sudo install ./dist/eatinst /usr/bin/eatinst
     - run: echo "Eat has been installed."
       shell: bash
